# Generated by Django 3.2.23 on 2025-11-12 19:00

import django.core.validators
from django.db import migrations, models
import dsmr_backend.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0033_fix_retention_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsmrMemoryReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=None, help_text='Timestamp indicating when the reading was taken, according to the smart meter', null=True)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the reading was inserted in the database')),
                ('electricity_delivered_1', models.DecimalField(decimal_places=3, default=0, help_text='Meter position stating electricity delivered (Dutch users: low tariff) in kWh', max_digits=9)),
                ('electricity_returned_1', models.DecimalField(decimal_places=3, default=0, help_text='Meter position stating electricity returned (Dutch users: low tariff) in kWh', max_digits=9)),
                ('electricity_delivered_2', models.DecimalField(decimal_places=3, default=0, help_text='Meter position stating electricity delivered (normal tariff) in kWh', max_digits=9)),
                ('electricity_returned_2', models.DecimalField(decimal_places=3, default=0, help_text='Meter position stating electricity returned (normal tariff) in kWh', max_digits=9)),
                ('electricity_currently_delivered', models.DecimalField(decimal_places=3, default=0, help_text='Current electricity delivered in kW', max_digits=9)),
                ('electricity_currently_returned', models.DecimalField(decimal_places=3, default=0, help_text='Current electricity returned in kW', max_digits=9)),
                ('phase_currently_delivered_l1', models.DecimalField(decimal_places=3, default=None, help_text='Current electricity used by phase L1 (in kW)', max_digits=9, null=True)),
                ('phase_currently_delivered_l2', models.DecimalField(decimal_places=3, default=None, help_text='Current electricity used by phase L2 (in kW)', max_digits=9, null=True)),
                ('phase_currently_delivered_l3', models.DecimalField(decimal_places=3, default=None, help_text='Current electricity used by phase L3 (in kW)', max_digits=9, null=True)),
                ('extra_device_timestamp', models.DateTimeField(default=None, help_text='Last timestamp read from the extra device connected (gas meter)', null=True)),
                ('extra_device_delivered', models.DecimalField(decimal_places=3, default=None, help_text='Last value read from the extra device connected (gas meter)', max_digits=9, null=True)),
                ('phase_currently_returned_l1', models.DecimalField(decimal_places=3, default=None, help_text='Current electricity returned by phase L1 (in kW)', max_digits=9, null=True)),
                ('phase_currently_returned_l2', models.DecimalField(decimal_places=3, default=None, help_text='Current electricity returned by phase L2 (in kW)', max_digits=9, null=True)),
                ('phase_currently_returned_l3', models.DecimalField(decimal_places=3, default=None, help_text='Current electricity returned by phase L3 (in kW)', max_digits=9, null=True)),
                ('phase_voltage_l1', models.DecimalField(decimal_places=1, default=None, help_text='Current voltage for phase L1 (in V)', max_digits=4, null=True)),
                ('phase_voltage_l2', models.DecimalField(decimal_places=1, default=None, help_text='Current voltage for phase L2 (in V)', max_digits=4, null=True)),
                ('phase_voltage_l3', models.DecimalField(decimal_places=1, default=None, help_text='Current voltage for phase L3 (in V)', max_digits=4, null=True)),
                ('phase_power_current_l1', models.IntegerField(default=None, help_text='Power/current for phase L1 (in A)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('phase_power_current_l2', models.IntegerField(default=None, help_text='Power/current for phase L2 (in A)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('phase_power_current_l3', models.IntegerField(default=None, help_text='Power/current for phase L3 (in A)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
            ],
            options={
                'verbose_name': 'DSMR reading',
                'verbose_name_plural': 'DSMR readings',
                'ordering': ['timestamp'],
                'default_permissions': (),
            },
            bases=(dsmr_backend.mixins.ModelUpdateMixin, models.Model),
        ),
    ]
